models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param  string  $email the target email address
     * @return boolean whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

models/LoginForm.php
<?php

namespace app\models;

use app\interfaces\obpattern\ObSubject;
use app\services\tickets\ObSubjectTrait;
use Yii;
use yii\base\Model;
use app\models\users\User;

/**
 * LoginForm is the model behind the login form.
 */
class LoginForm extends Model implements ObSubject
{
    use ObSubjectTrait;

    public $username;
    public $password;
    public $rememberMe = true;

    private $user = false;

    public function init()
    {
        $this->observers = new \SplObjectStorage();
    }

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'username' => 'Имя пользователя',
            'password' => 'Пароль',
            'rememberMe' => 'Запомнить меня'
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return boolean whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            if (Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0)) {
                // Ob notification
                $this->notify('login', $this);
                return true;
            }

            return false;
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->user === false) {
            $this->user = User::findByUsername($this->username);
        }

        return $this->user;
    }
}

models/LoginLogObServer.php
<?php

namespace app\models;

use Yii;
use app\services\user\UserLoggerFactory;
use app\interfaces\obpattern\ObServer;
use app\interfaces\obpattern\ObSubject;

/**
 * Class LoginLog
 * @package app\models
 */
class LoginLogObServer implements ObServer
{
    const MAIN_ACTION = 'login';

    /**
     * @inheritdoc
     */
    public function update($action, ObSubject $subject, $message = null)
    {
        if ($action === self::MAIN_ACTION) {
            $ul = UserLoggerFactory::create();
            $ul->log();
        }
    }
}

controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use app\controllers\system\Controller;
use app\services\user\UserLoggerFactory;
use app\models\LoginLogObServer;
use app\models\LoginForm;

/**
 * Class AuthController
 * @package app\controllers
 */
class AuthController extends Controller
{
    public $layout = 'auth';

    /**
     * The user logs into the account on the basis of a
     * standard authorization
     *
     * @link https://github.com/yiisoft/yii2-app-basic/blob/master/controllers/SiteController.php#L55
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            $this->goBack();
        }

        $loginForm = new LoginForm();
        // Логирование входов
        $loginForm->attach(new LoginLogObServer());

        if ($loginForm->load(Yii::$app->getRequest()->post()) && $loginForm->login()) {
            // Redirect to dashboard
            $this->redirect(['/']);
        }

        return $this->render('login', [
            'model' => $loginForm,
        ]);
    }

    /**
     * The exit of the account
     *
     * @link https://github.com/yiisoft/yii2-app-basic/blob/master/controllers/SiteController.php#L70
     */
    public function actionLogout()
    {
        $ul = UserLoggerFactory::create();
        $ul->log($ul::ACT_LOGOUT);

        Yii::$app->getUser()->logout();

        $this->goHome();
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\controllers\system\SecurityController;
use Yii;
use app\models\ContactForm;

/**
 * Class SiteController
 *
 * @package app\controllers
 */
class SiteController extends SecurityController
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/pageElements/breadcrumbs.php
<?php

/** @var yii\web\View $this */
use yii\widgets\Breadcrumbs;
use rmrevin\yii\fontawesome\FA;

?>

<?php if (array_key_exists('breadcrumbs', $this->params)) : ?>
    <section class="breadcrumbs-container">
        <div class="container">
            <?= Breadcrumbs::widget([
                'encodeLabels' => false,
                'homeLink' => [
                    'label' => FA::icon('home').'&nbsp;&nbsp;Главная',
                    'url' => ['/'],
                ],
                'links' => $this->params['breadcrumbs'],
            ]); ?>
        </div>
    </section>
<?php endif; ?>

views/layouts/pageElements/footer.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;

?>

<footer>
    <div class="container">
        © <?= date('Y'); ?>. <?= Html::a('Bingo37', ['site/index']); ?>
    </div>
</footer>

views/layouts/pageElements/leftSidebar.php
<?php

/** @var yii\web\View $this */
use rmrevin\yii\fontawesome\FA;
use yii\widgets\Menu;
use yii\helpers\Html;
use app\models\users\User;

?>

<span class="block-title">
    Главное меню
</span>

<div class="block-user">
    <div class="media">
        <div class="media-left">
            <?= $this->render('userImage'); ?>
        </div>
        <div class="media-body media-middle">
            <h4 style="margin: 0;"><?= Html::encode(Yii::$app->getUser()->getIdentity()->fullName); ?></h4>
            <h5>
                <?php $roles = Yii::$app->getAuthManager()->getRolesByUser(Yii::$app->getUser()->getId()); ?>
                <?php foreach ($roles as $role) : ?>
                    <?= $role->description; ?>
                <?php endforeach; ?>
            </h5>
        </div>
    </div>
</div>

<?= Menu::widget([
    'activeCssClass' => 'active',
    'encodeLabels' => false,
    'items' => [
        [
            'label' => FA::icon('dashboard').'&nbsp;&nbsp;Dashboard',
            'url' => ['/dashboard/default/index']
        ],
        [
            'label' => FA::icon('credit-card').'&nbsp;&nbsp;Отчет по финансам',
            'url' => ['/statistics/money/index'],
        ],
        [
            'label' => FA::icon('bar-chart').'&nbsp;&nbsp;Статистика',
            'url' => ['/statistics/default/index'],
        ],
        [
            'label' => FA::icon('chain-broken').'&nbsp;&nbsp;Статистика по терминалам',
            'url' => ['/statistics/terminals/index'],
        ],
        [
            'label' => FA::icon('ticket').'&nbsp;&nbsp;Создать билет',
            'url' => ['/tickets/tickets/create'],
        ],
        [
            'label' => FA::icon('money').'&nbsp;&nbsp;Выплатить по билету',
            'url' => ['/tickets/payment/pay'],
        ],
        [
            'label' => FA::icon('th-list').'&nbsp;&nbsp;Список билетов',
            'url' => ['/tickets/tickets/index'],
        ],
        [
            'label' => FA::icon('cogs').'&nbsp;&nbsp;Настройки',
            'visible' => Yii::$app->getUser()->can(User::SUPERADMIN_ROLE),
            'active' => (Yii::$app->controller->module->id === 'settings'),
            'url' => ['/settings'],
        ],
        [
            'label' => FA::icon('user-plus').'&nbsp;&nbsp;Управление пользователями',
            'visible' => Yii::$app->getUser()->can(User::SUPERADMIN_ROLE),
            'url' => ['/users/user/index'],
        ],
        [
            'label' => FA::icon('get-pocket').'&nbsp;&nbsp;Пользовательские логи',
            'visible' => Yii::$app->getUser()->can(User::SUPERADMIN_ROLE),
            'url' => ['/users/login-log/index'],
        ],
        [
            'label' => FA::icon('terminal').'&nbsp;&nbsp;Управление терминалами',
            'visible' => Yii::$app->getUser()->can(User::SUPERADMIN_ROLE),
            'url' => ['/terminals/crud/index'],
        ],
        [
            'label' => FA::icon('star').'&nbsp;&nbsp;Управление ставками',
            'visible' => Yii::$app->getUser()->can(User::SUPERADMIN_ROLE),
            'url' => ['/rates/crud/index'],
        ],
    ],
    'options' => ['class' => 'nav nav-pills nav-stacked main-nav'],
]); ?>

views/layouts/pageElements/pageTop.php
<header>
    <?= $this->render('topNavbar'); ?>
    <?= $this->render('breadcrumbs'); ?>
</header>

views/layouts/pageElements/topNavbar.php
<?php

/** @var yii\web\View $this */
use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;
use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;

?>

<?php NavBar::begin([
    'brandLabel' => 'Bingo37',
    'options' => ['class' => 'nav navbar-inverse'],
]); ?>

<?= Nav::widget([
    'encodeLabels' => false,
    'dropDownCaret' => false,
    'items' => [
        ['label' => 'example', 'url' => '#', 'visible' => !Yii::$app->getUser()->isGuest],
        [
            'dropDownOptions' => ['class' => 'dropdown-menu-right'],
            'visible' => !Yii::$app->getUser()->isGuest,
            'label' => $this->render('userImage'),
            'items' => [
                ['label' => FA::icon('sign-out').'&nbsp;&nbsp;Выйти из профиля', 'url' => ['/auth/logout']],
            ],
        ]
    ],
    'options' => ['class' => 'nav navbar-nav pull-right top-nav'],
]); ?>

<?php NavBar::end(); ?>

views/layouts/pageElements/userImage.php
<?php use yii\helpers\Html; ?>

<?php if (!Yii::$app->getUser()->getIsGuest()) : ?>
    <?php
        $imageUrl = Yii::$app
            ->getUser()
            ->getIdentity()
            ->getThumbFileUrl('photo', 'thumb', Yii::getAlias('@web').'/images/noavatar.png');
    ?>
    <?= Html::img($imageUrl, ['class' => 'img-circle img-sm']); ?>
<?php endif; ?>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use barcode\barcode\BarcodeGenerator;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="block">
    <div class="media" id="ticket">
        <div class="media-left media-middle">
            <div id="barcode" class="pull-left"></div>
            <?= BarcodeGenerator::widget([
                'elementId' => 'barcode',
                'type'      => 'ean13',
                'value'     => rand(1000000000000, 9999999999999),
                'settings'  => [
                    'barWidth' => 2,
                    'barHeight' => 80,
                ],
            ]); ?>
        </div>
        <div class="media-body text-center text-uppercase">
            <h1 class="ticket-title">Bingo 37</h1>
            <p>Лотерейный билет</p>
            <div class="row">
                <div class="col-xs-4 text-left"><h5>8 (999) 999 - 9999</h5></div>
                <div class="col-xs-4"><h5>г.Санкт-Петербург, улица Кропоткина 1</h5></div>
                <div class="col-xs-4 text-right"><h5>bingo37.su</h5></div>
            </div>

            <h1><?= number_format(9353.62, 2); ?> kzt</h1>

            <div class="row">
                <div class="col-xs-6">
                    <p class="text-justify">
                        Билет не является средством оплаты
                    </p>
                </div>
                <div class="col-xs-6 text-right">
                    <p>Администратор: Петров Сергей</p>
                    <p><?= date('d.m.Y H:i'); ?></p>
                </div>
            </div>
        </div>
        <hr />
    </div>
</div>
<br />

<button class="print btn btn-success">print</button>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';

$this->params['breadcrumbs'][] = 'Dashboard';

?>

<div class="row">
    <div class="col-md-3">1</div>
    <div class="col-md-3">2</div>
    <div class="col-md-3">3</div>
    <div class="col-md-3">4</div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>